### PR TITLE
fix operation on iPhoneOS Safari

### PR DESCRIPTION
**Pull request by mirabilos**
contributing fix from my map experiment repo as requested by https://github.com/stefanocudini/leaflet-compass/issues/15#issuecomment-1348639017

fixes the situation for iPhoneOS; “should not” affect others, but I haven’t been able to test them much; my employer’s Samsung Android has it working in Google Chrome but showing just 0° on Firefox Fennec from F-Droid but I don’t think it was working there before?

### CODE REVIEW

**Comment by stefanocudini** [comment]
never tested on Fennec tnks

**Comment by stefanocudini** [comment]
published new version here if you want check: https://opengeo.tech/maps/leaflet-compass/

**Comment by mirabilos** [comment]
Stefano Cudini dixit:

>published new version here if you want check: https://opengeo.tech/maps/leaflet-compass/

Works-ish: it does work, but the numbers go down from 0° to -360° (yes,
I could get both these numbers and most in between).

bye,
//mirabilos
-- 
>> Why don't you use JavaScript? I also don't like enabling JavaScript in
> Because I use lynx as browser.
+1
	-- Octavio Alvarez, me and ⡍⠁⠗⠊⠕ (Mario Lang) on debian-devel

**Comment by stefanocudini** [comment]
tnks @mirabilos 

Can I ask you a favor to create an issue for this? including a screenshot..

unfortunately I don't have much free time to fix the problems of this repository and I need some help from the community, it's a particular plugin that requires various tests on various devices (which I don't have).
I hope other devs passing through the repository will give us a hand

cheers!

P.S.
my public request here:
https://groups.google.com/g/leaflet-js/c/LFxHSDzBJao

**Comment by mirabilos** [comment]
Stefano Cudini dixit:

>Can I ask you a favor to create an issue for this? including a screenshot..

Uhm, I’d rarher not spoil my location by giving a screenshot.

I can, however, say that my own map experiment using
leaflet-compass’ commit e0ca0e9920fcd8e14479f004da11f76aa7d10339
plus the fixes I’ve provided *does* work, so it must have been
a regression introduced in e0ca0e9..e545d99 and/or 03ef5bf..a1c36f3

Maybe this helps ☺

>unfortunately I don't have much free time to fix the problems of this
>repository and I need some help from the community, it's a particular
>plugin that requires various tests on various devices (which I don't
>have).

I know the problem…

>I hope other devs passing through the repository will give us a hand

Indeed!

bye,
//mirabilos
-- 
16:47⎜«mika:#grml» .oO(mira ist einfach gut....)      23:22⎜«mikap:#grml»
mirabilos: und dein bootloader ist geil :)    23:29⎜«mikap:#grml» und ich
finds saugeil dass ich ein bsd zum booten mit grml hab, das muss ich dann
gleich mal auf usb-stick installieren	-- Michael Prokop über MirOS bsd4grml

**Pull request merged**
